// СОздание каталога товаров
const CATALOG = [
  {
    id: "el1",
    name: "White",
    img: "./img/345.png",
    price: "300",
    filter: "middle",
    text:"Sure, here you go:The serene sunset painted the sky with hues of orange and pink, creating a breathtaking view.",
  },
  {
    id: "el1",
    name: "White",
    img: "./img/345.png",
    price: "300",
    filter: "middle",
    text:"Sure, here you go:The serene sunset painted the sky with hues of orange and pink, creating a breathtaking view.",
  },
  {
    id: "el1",
    name: "White",
    img: "./img/345.png",
    price: "300",
    filter: "middle",
    text:"Sure, here you go:The serene sunset painted the sky with hues of orange and pink, creating a breathtaking view.",
  },
  {
    id: "el2",
    name: "Black",
    img: "./img/345.png",
    price: "500",
    filter: "rich",
    text:"Sure, here you go:The serene sunset painted the sky with hues of orange and pink, creating a breathtaking view.",
  },
  {
    id: "el2",
    name: "Black",
    img: "./img/345.png",
    price: "500",
    filter: "rich",
    text:"Sure, here you go:The serene sunset painted the sky with hues of orange and pink, creating a breathtaking view.",
  },
  {
    id: "el2",
    name: "Black",
    img: "./img/345.png",
    price: "500",
    filter: "rich",
    text:"Sure, here you go:The serene sunset painted the sky with hues of orange and pink, creating a breathtaking view.",
  },
  {
    id: "el3",
    name: "Blue",
    img: "./img/345.png",
    price: "100",
    filter: "chip",
    text:"Sure, here you go:The serene sunset painted the sky with hues of orange and pink, creating a breathtaking view.",
  },
  {
    id: "el3",
    name: "Blue",
    img: "./img/345.png",
    price: "100",
    filter: "chip",
    text:"Sure, here you go:The serene sunset painted the sky with hues of orange and pink, creating a breathtaking view.",
  },
  {
    id: "el3",
    name: "Blue",
    img: "./img/345.png",
    price: "100",
    filter: "chip",
    text:"Sure, here you go:The serene sunset painted the sky with hues of orange and pink, creating a breathtaking view.",
  },
];
